francis_ilagan_onboarding/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include("polls.urls"))
]

polls/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = "polls"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.utils import timezone

from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField("date published")
	def __str__(self):
		return self.question_text;
	def is_recent(self):
		sDate = timezone.now() - datetime.timedelta(days=1)
		return sDate <= self.pub_date <= timezone.now()
	is_recent.admin_order_field = "pub_date"
	is_recent.boolean = True
	is_recent.short_description = "Is Published Recently?"


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text;

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone
from django.views import generic
from django.shortcuts import render, get_object_or_404

from django.urls import reverse

from django.http import HttpResponse, Http404, HttpResponseRedirect

from .models import Question, Choice

class IndexView(generic.ListView):
	template_name = "polls/index.html"
	context_object_name = "latest_questions"
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = "polls/detail.html"
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultView(generic.DetailView):
	model = Question
	template_name = "polls/result.html"	
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		sChoice = question.choice_set.get(pk=request.POST["qChoice"])
	except(KeyError, Choice.DoesNotExist):
		return render(request, "polls/detail.html", {
				"question": question,
				"error_message": "You have selected nothing."
			})
	else:
		sChoice.votes += 1
		sChoice.save()
		return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>

{%if error_message%}
	<h4>{{error_message}}</h4>
{%endif%}
{%if question.choice_set.all%}
	<form action="{%url 'polls:vote' question.id%}" method="post">
		{% csrf_token %} 
		{%for c in question.choice_set.all%}
			<input type="radio" name="qChoice" id="qChoice{{forloop.counter}}" value="{{c.id}}"/>
			<label for="qChoice{{forloop.counter}}">{{c.choice_text}}</label>
			<br/>
		{%endfor%}
		<input type="submit" value="Vote"/>
	</form>
{%endif%}

polls/templates/polls/index.html
{%load static%}

<link rel="stylesheet" type="text/css" href="{%static 'polls/style.css'%}"/>

<h1>Question List</h1>

{%if latest_questions%}
	<ul>
		{%for q in latest_questions%}
			<li><a href="{%url 'polls:detail' q.id%}">{{q.question_text}}</a></li>
		{%endfor%}
	</ul>
{%else%}
	<h4>No questions found.</h4>
{%endif%}

polls/templates/polls/result.html
<h1>{{question.question_text}}</h1>

<table>
	<thead>
		<th>Choice</th>
		<th># of Votes</th>
	</thead>
	<tbody>
		{%for c in question.choice_set.all|dictsortreversed:"votes"%}
			<tr>
				<td>{{c.choice_text}}</td>
				<td>{{c.votes}}</td>
			</tr>
		{%endfor%}
	</tbody>
</table>

<a href="{%url 'polls:detail' question.id%}">Return</a>